### PR TITLE
cbattenfield-box-sweep-signoff

### PR DESCRIPTION
**Pull request by cebttu**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
No buildable schematic. Comments on electrical design made in person.

**Review by JesseTNRoberts — COMMENTED** [review]
Why the iso standard? 

How much force does the arm have to withstand when it moves the boxes?

**Review by JesseTNRoberts — COMMENTED** [review]
This looks like good progress but I don't think it is ready for a review at this point.

**Review by JesseTNRoberts — COMMENTED** [review]
See the comment about the electrical schematic for the button pusher. same applies here.

**Review by JesseTNRoberts — COMMENTED** [review]
comment not addressed.

**Comment by arc2448** [comment]
Added the completed diagrams. Had a computer crash this weekend and lost editing progress that had not been restored, my bad.

**Review by JesseTNRoberts — APPROVED** [review]

**Pull request merged**
