### PR TITLE
LiamCounasse-signoff-Team_Spirit

### PR DESCRIPTION
**Pull request by LiamCounasse**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
constraints don't meet the criteria set by the team. This has been said numerous times. Why is it not fixed?

**Comment by arc2448** [comment]
Still missing a constraint discussed yesterday. Also need to include where the constraint comes from in the table.

**Review by JesseTNRoberts — COMMENTED** [review]
This looks good. I have a couple of questions. first, are you sure the microcontroller can drive that many diodes? 

2nd, great point about not putting the diodes on the front. But in that case how ca we guarantee that the bot is undeniably TTU from all angles? Can we add something non-illuminated just to the front?

**Review by JesseTNRoberts — COMMENTED** [review]
Address the concerns regarding the switching speed

**Review by JesseTNRoberts — COMMENTED** [review]
So, these can switch 10 times per second. That means they can complete 5 periods of a square wave in a second.  So, they are capable of 5 hz. However, this means constant switching. How long before the relay coil burns out? (Typically, there are a maximum number of times that the relay will actually be able to switch before the coil is burned or the contacts are welded)

**Review by JesseTNRoberts — COMMENTED** [review]
The schematic does not make sense. The connections don't allow the transistor to control the LEDs. Also, I don't see any analysis of the current through the mosfet showing this will work.

**Review by JesseTNRoberts — COMMENTED** [review]
Did not address all of previous feedback.

**Review by JesseTNRoberts — COMMENTED** [review]
I don't know what the current graph is supposed to show. The simulation should convince you and me that it will work. 

How does the graph accomplish that?

**Review by JesseTNRoberts — COMMENTED** [review]
Same comment.

Don't write more words. Consider the feedback and honestly evaluate if what is present in the simulation guarantees to you that this will work. Ask your teammates. If not, why? 

The design is good. However, me knowing that isn't sufficient. You have to be able to justify why it is or isn't good.

**Review by JesseTNRoberts — APPROVED** [review]

**Pull request merged**
